### ISSUE TITLE
Service provider logo

### ISSUE THREAD

**Issue by AdAvAn** [saltedge/saltedge-ios-swift#38]
Hello.

I am using your SDK for iOS, and I see that the `SEProvider` model does not contain an attribute with a link to the provider's logo. 

This attribute `logo_url` is listed with the API [providers-attributes](https://docs.saltedge.com/account_information/v5/#providers-attributes), but I can’t use it in my project

Please add it to the provider model.
Thanks

**Comment by ConstantinKV** [comment]
Hello @AdAvAn . Thank you for your contribution. 
We have added `logoURL` to SEProvider model. 
Please check the last pod `3.3.1`.

**Comment by AdAvAn** [comment]
Hello @ConstantinKV .

I updated a new version (3.3.1), i see `logoURL` in the SEProvider model, excellent, thanks for your help!
