### ISSUE TITLE
Regarding URL scheme callback

### ISSUE THREAD

**Issue by ankitjaiswal1994** [saltedge/saltedge-ios-swift#4]
Certainly it is not a issue, but unable to understand the use of code written in Appdelegate, Please check it below : 

```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        if let createVC = createViewController {
            HUD.show(.labeledProgress(title: "Fetching OAuth Login", subtitle: nil))
            SERequestManager.shared.handleOpen(url: url, loginFetchingDelegate: createVC)
        }
        return true
    }
```

Could you please explain when it get called.

**Comment by v-somov** [comment]
You can find here when this method is called: https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application

In the example app it is needed for connecting OAuth login. You can find more information about oauth provider here: https://docs.saltedge.com/v4_apps/reference/#oauth_providers

When you are trying to connect OAuth provider in request you are sending `return_to` url which should be a url associated with your app (url scheme): https://github.com/saltedge/saltedge-ios-swift/blob/master/Example/saltedge-ios/View%20Controllers/CreateViewController.swift#L110. 
In response you will get a `redirect_url` to which you should redirect: https://github.com/saltedge/saltedge-ios-swift/blob/master/Example/saltedge-ios/View%20Controllers/CreateViewController.swift#L110. After user provides Salt Edge access to their financial data, he will be redirected using `return_to` url, so the user will be redirected back to the app.

**Comment by ankitjaiswal1994** [comment]
Perfect got it.

Very much Appreciated!

Thanks for your quick reply.
