### ISSUE TITLE
missing? duplicated connection callback

### ISSUE THREAD

**Issue by BlixLT** [saltedge/saltedge-ios-swift#59]
Am I missing something or is there no duplicated connection callback anymore (that was in the earlier - deprecated - saltedge-ios (https://github.com/saltedge/saltedge-ios) API)? Try creating a new connection to some bank, enter some invalid credentials (connection fails, but it still being created). Then select that provider from the providers list again and try entering the same credentials - an error message "Server Error. You have already used these credentials to connect this provider" is being displayed in the webview, but no callback being received by api. I tried with the sample app. I think the same thing happens if first connection is being created successfully. If you try select provider and enter same credentials again - an error is being displayed on top of the webview, but no callback with duplicated connection id/secret is being received by api.
Is it a bug or am I missing something?

**Comment by baller784** [comment]
Hello @BlixLT!

Thank you for your contribution. Currently we're investigating your issue. Will get back to you with an answer soon.

**Comment by BlixLT** [comment]
An update: probably it was a server problem, not the SDK. Today I am being able to receive duplicated connection callback (with a connection id) using steps described earlier. So, I guess this issue can be closed.

**Comment by baller784** [comment]
> An update: probably it was a server problem, not the SDK. Today I am being able to receive duplicated connection callback (with a connection id) using steps described earlier. So, I guess this issue can be closed.

Yes, the problem was on the server side. Glad, that everything is ok. Thank you again for your contribution.
