### ISSUE TITLE
ConsentRouter.show() parameters bug

### ISSUE THREAD

**Issue by BlixLT** [saltedge/saltedge-ios-swift#67]
I think there is a bug in ConsentRouter.show() parameters. Both .show() and .revoke() uses SEBaseConsentsParams (that are Encodable, ParametersEncodable). While with revoke() its ok I think (although I haven't tested it), but this causes problems with .show(), that uses GET method - Encodable parameters are being put into urlRequest's httpBody property. 
So, as far as I understand, parameters used in .show() (and probably in .list(), that is also using GET method) should be URLEncodable (but not Encodable). That way parameters will be appended to the request's url.

**Comment by ConstantinKV** [comment]
@BlixLT thank you for your contribution. We will investigate your issue and we will reply you ASAP.

**Comment by baller784** [comment]
@BlixLT Hi. This bug is already fixed in `3.3.14`. Please update.

**Comment by baller784** [comment]
@BlixLT I think we can close this issue. If you have any questions, please open a new one. Thank you.
