### ISSUE TITLE
SEConsentListParams dictionaryRepresentation bug

### ISSUE THREAD

**Issue by BlixLT** [saltedge/saltedge-ios-swift#69]
`SEConsentListParams` is a subclass of `SEBaseConsentsParams`, however `dictionaryRepresentation` method (of a protocol `URLEncodable`) takes properties only from `SEConsentListParams` class itself (it does not take inherited properties from `SEBaseConsentsParams`). 

Lets say you create `SEConsentListParams(perPage:"1000", connectionId:"someID")`. When encoded to url it will look like "`.../consents/?per_page=1000`" - there will be no parameter connection_id in the URL.

As far as I can tell `Mirror(reflecting:self)` (used in `URLEncodable.dictionaryRepresentation`)  takes properties only from `self`. Looks like one way to get properties from the parent class could be later calling `mirror.superclassMirror` and process it the same way as `mirror`.

**Comment by baller784** [comment]
@BlixLT Thank you for your contribution and bug reporting. Will be fixed ASAP.

**Comment by baller784** [comment]
@BlixLT Please update to the latest SaltEdge iOS SDK version - `3.4.0`. Thank you.
